package structs

type Hero struct {
	Name                string        `json:"name"`
	Godname             string        `json:"godname"`
	Gender              string        `json:"gender"`
	GGender             string        `json:"g_gender"`
	GoldApprox          string        `json:"gold_approx"`
	Level               int           `json:"level"`
	Quest               string        `json:"quest"`
	QuestProgress       int           `json:"quest_progress"`
	ExpProgress         int           `json:"exp_progress"`
	Health              uint16        `json:"health"`
	MaxHealth           uint16        `json:"max_health"`
	InventoryNum        uint16           `json:"inventory_num"`
	InventoryMaxNum     uint16           `json:"inventory_max_num"`
	Alignment           string        `json:"alignment"`
	Motto               string        `json:"motto"`
	Clan                string        `json:"clan"`
	TimeZone            string        `json:"time_zone"`
	DiaryLast           string        `json:"diary_last"`
	TempleCompletedAt   string        `json:"temple_completed_at"`
	MfAt                interface{}   `json:"mf_at"`
	ArkCompletedAt      string        `json:"ark_completed_at"`
	Distance            uint16        `json:"distance"`
	TownName            string        `json:"town_name"`
	InTown              bool          `json:"in_town"`
	ArenaFight          bool          `json:"arena_fight"`
	BricksCnt           int           `json:"bricks_cnt"`
	Wood                string        `json:"wood"`
	WoodCnt             int           `json:"wood_cnt"`
	Godpower            uint8         `json:"godpower"`
	ClanPosition        string        `json:"clan_position"`
	ACmd                bool          `json:"a_cmd"`
	PetsMax             int           `json:"pets_max"`
	AuraName            string        `json:"aura_name"`
	Retirement          string        `json:"retirement"`
	Au                  int           `json:"au"`
	UPhr                bool          `json:"u_phr"`
	ArenaWon            int           `json:"arena_won"`
	ArenaLost           int           `json:"arena_lost"`
	InventorySerial     int           `json:"inventory_serial"`
	MaxGp               int           `json:"max_gp"`
	Gold                int           `json:"gold"`
	GoldWe              string        `json:"gold_we"`
	MonstersKilled      int           `json:"monsters_killed"`
	DeathCount          int           `json:"death_count"`
	IsArenaAvailable    bool          `json:"is_arena_available"`
	DA                  bool          `json:"d_a"`
	SA                  bool          `json:"s_a"`
	RA                  bool          `json:"r_a"`
	IsChfAvailable      bool          `json:"is_chf_available"`
	ChfPending          string        `json:"chf_pending"`
	AgeStr              string        `json:"age_str"`
	Accumulator         float32       `json:"accumulator"`
	QuestsCompleted     int           `json:"quests_completed"`
	Aln                 string        `json:"aln"`
	Dir                 string        `json:"dir"`
	MId                 string        `json:"m_id"`
	MIdN                string        `json:"m_id_n"`
	MonsterName         string        `json:"monster_name"`
	MonsterProgress     uint16        `json:"monster_progress"`
	SProgress           float64       `json:"s_progress"`
	ArenaSendAfter      int           `json:"arena_send_after"`
	DSendAfter          int           `json:"d_send_after"`
	SSendAfter          int           `json:"s_send_after"`
	RAfter              int           `json:"r_after"`
	RT                  interface{}   `json:"r_t"`
	ChfrAfter           int           `json:"chfr_after"`
	IsArenaDisabled     bool          `json:"is_arena_disabled"`
	AuraTime            int           `json:"aura_time"`
	Q2T                 string        `json:"q2t"`
	Q2                  []interface{} `json:"q2"`
	CTown               string        `json:"c_town"`
	Lte                 string        `json:"lte"`
	Poi                 []int         `json:"poi"`
	InvM                string        `json:"inv_m"`
	InvitesLeft         int           `json:"invites_left"`
	Ggender             string        `json:"ggender"`
	ArenaGodCmdDisabled bool          `json:"arena_god_cmd_disabled"`
}
